# TCL File Generated by Component Editor 9.1
# Tue Oct 18 20:11:49 CST 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | motor "motor" v1.0
# | null 2011.10.18.20:11:49
# | 
# | 
# | E:/ssl_workspace/motorcontrol_20110630/motor.v
# | 
# |    ./motor.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module motor
# | 
set_module_property NAME motor
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP Communication
set_module_property DISPLAY_NAME motor
set_module_property TOP_LEVEL_HDL_FILE motor.v
set_module_property TOP_LEVEL_HDL_MODULE motor
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file motor.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
add_interface_port clock_reset rst_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 associatedClock clock_reset
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ASSOCIATED_CLOCK clock_reset
set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 rd_n read_n Input 1
add_interface_port avalon_slave_0 wr_n write_n Input 1
add_interface_port avalon_slave_0 cs_n chipselect_n Input 1
add_interface_port avalon_slave_0 rddata readdata Output 32
add_interface_port avalon_slave_0 wrdata writedata Input 32
add_interface_port avalon_slave_0 addr address Input 3
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ASSOCIATED_CLOCK clock_reset
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end code0 export Input 32
add_interface_port conduit_end code1 export Input 32
add_interface_port conduit_end code2 export Input 32
add_interface_port conduit_end code3 export Input 32
add_interface_port conduit_end set export Output 32
add_interface_port conduit_end A export Output 32
add_interface_port conduit_end B export Output 32
add_interface_port conduit_end Z_Brushless export Output 1
add_interface_port conduit_end Z_OpenLoop export Output 1
# | 
# +-----------------------------------
