# TCL File Generated by Component Editor 9.1
# Thu Jun 10 14:04:04 CST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | shoot_timer "shoot_timer" v1.0
# | null 2010.06.10.14:04:04
# | 
# | 
# | F:/small/improve/FPGA/SMALL_0609/shoot_timer/shoot_timer.v
# | 
# |    ./shoot_timer.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module shoot_timer
# | 
set_module_property NAME shoot_timer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP Communication
set_module_property DISPLAY_NAME shoot_timer
set_module_property TOP_LEVEL_HDL_FILE shoot_timer.v
set_module_property TOP_LEVEL_HDL_MODULE shoot_timer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file shoot_timer.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter Bit_32 INTEGER 24
set_parameter_property Bit_32 DEFAULT_VALUE 24
set_parameter_property Bit_32 DISPLAY_NAME Bit_32
set_parameter_property Bit_32 UNITS None
set_parameter_property Bit_32 DISPLAY_HINT ""
set_parameter_property Bit_32 AFFECTS_GENERATION false
set_parameter_property Bit_32 HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
add_interface_port clock_reset reset reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 associatedClock clock_reset
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ASSOCIATED_CLOCK clock_reset
set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 wrdata writedata Input Bit_32
add_interface_port avalon_slave_0 wr_n write_n Input 1
add_interface_port avalon_slave_0 rd_n read_n Input 1
add_interface_port avalon_slave_0 rddata readdata Output Bit_32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ASSOCIATED_CLOCK clock_reset
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end Dout export Output 1
# | 
# +-----------------------------------
